### ISSUE TITLE
API selection

### ISSUE THREAD

**Issue by BosamiyaSimran** [BosamiyaSimran/SE-Project-Group-15#4]
Research and decide which api to use for translation.

**Comment by freakNewton** [comment]
I searched on web and found that LibreTranslate has a free API but I am having difficulty in getting a API key. Still trying to search more on this.

**Comment by BosamiyaSimran** [comment]
Let us use googletranslate API. It is free for around 5000 words. Started working on implementing the same. Created project on google cloud account and generated API key. Facing issue in calling library functions.

**Comment by freakNewton** [comment]
Ok let's use that and start the project. We can transition to other API if needed. I am closing this issue now.
